# Fortran GCC compiler
FC=gfortran

# compilation flags: check out the Python notebook for examples
# or get one of the flags from here: https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html 
FDFLAGS=

# source files
SOURCE=./matmul.f90

all:
	$(FC) $(FDFLAGS) $(SOURCE)
	@echo -e "----- COMPILATION DONE -----"


clean:
	rm ./a.out

