# Fortran GCC compiler
CC=gcc

# compilation flags: check out the Python notebook for examples
# or get one of the flags from here: https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html 
LDFLAGS=

# source files
SOURCE=./saxpy.c

all:
	$(CC) $(LDFLAGS) $(SOURCE)
	@echo -e "----- COMPILATION DONE -----"


clean:
	rm ./a.out

